### ISSUE TITLE
SQL Server: column 'auth_token' exceeds the maximum allowed for any data type (8000)

### ISSUE THREAD

**Issue by chunkai-meng** [MrThearMan/django-signal-webhooks#26]
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.2.4

### Which python version are you using?

3.11

### What operating system are you on?

Ubuntu

### Description
Hi @MrThearMan,

When migrating on MSSQL DB encountered:

```
django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The size (10000) given to the column 'auth_token' exceeds the maximum allowed for any data type (8000). (131) (SQLExecDirectW)")
```
is it possible to set a `WebhookBase.auth_token` max_length of 8000 or lower? if that is the case.

Thank you for your time.

**Comment by MrThearMan** [comment]
Hi, thanks for the report!

I guess this is a MSSQL limitation. I'll look into other databases to see if other such limitations exist and lower the value appropriately. Meanwhile, you can subclass the Webhook model and change the field that way.
